parentDomain: k8s01.oleconsignado.com.br,
replicaCount: 1
image:
  repository: oleconsignado/stdprocessoavaliacao,
  tag: 0
dockerRegistrationSecret: ole-docker-reg

# Runtime
ASPNETCORE_ENVIRONMENT: "Development"
ApplicationInsights__Enabled: "false"
TZ: "America/Sao_Paulo"

AllowedHosts: "*"
RequestTrackerConfiguration__RequestTrackerEnabled: "true"
DistributedCacheConfiguration__CacheStorageType: "SqlServer"
DistributedCacheConfiguration__CacheSqlConnectionString: "Data Source=OLESQLHML,1433;Initial Catalog=OleCache;User Id=u_olaadmin;Password=u_0l@@dm1n;Application Name=olesinstdentradapropostaswebapi;,;Application Name=stdprocessoavaliacao,;"
DistributedCacheConfiguration__CacheSqlSchemaName: "dbo"
DistributedCacheConfiguration__CacheSqlTableName: "CacheTable"

# Log
Serilog__MinimumLevel__Default: Warning
Serilog__MinimumLevel__Override__Ole: Information
Serilog__MinimumLevel__Override__Otc: Information

# Core
# variaveis de ambiente que afetam comportamentos de negocio

# Tmdb
TmdbAdapterConfiguration__TmdbApiUrlBase: "https://api.themoviedb.org/3"
TmdbAdapterConfiguration__TmdbApiKey: "1f54bd990f1cdfb230adb312546d765d"
TmdbAdapterConfiguration__TempoDeCacheDaPesquisaEmSegundos: 30
TmdbAdapterConfiguration__Idioma: "pt-BR"

# DB
# strings de conexao com banco de dados

# Recursos
memoryRequest: "256Mi"
cpuRequest: "100m"
memoryLimit: "384Mi"
cpuLimit: "400m"

# Jwt
JwtConfiguration__Audience: "stdprocessoavaliacao,"
JwtConfiguration__Issuer: "stdprocessoavaliacao,"
JwtConfiguration__SecretKey: "85760141-c8c3-4896-b6d2-b6cad426a715"
